import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="px-8 mt-10">
      <Head>
        <title>Article Preview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-auto md:w-4/6 md:flex md:flex-row md:h-auto md:max-h-72">
        <img
          className="rounded-tr-md rounded-tl-md h-48 w-full md:h-auto md:w-2/5 md:rounded-bl-md md:rounded-tr-none image"
          src="/images/drawers.jpg"
          alt=""
        />
        <div className="bg-white p-8 rounded-bl-md rounded-br-md md:w-3/5 md:rounded-bl-none md:rounded-tr-md">
          <h2 className="text-gray-700 font-semibold">
            Redecora tu casa y dale un toque de color y frescura
          </h2>
          <p className="text-sm text-gray-600 mt-4">
            Alguna vez has estado en una habitación y has sentido ese ambiente
            no acogedor y poco relajante? Te doy algunos consejos para que tu
            habitación sea lo más acogedora posible!
          </p>
          <div className="flex items-center mt-8">
            <div className="flex items-center">
              <img
                className="h-10 w-10 rounded-full"
                src="/images/avatar-michelle.jpg"
                alt=""
              />
              <div className="ml-4">
                <p className="text-gray-800 text-sm font-semibold">
                  Jorge Herrando
                </p>
                <p className="text-gray-600 text-sm">5 Dec 2021</p>
              </div>
            </div>
            <div className="w-8 h-8 ml-auto bg-gray-200 rounded-full flex items-center justify-center">
              <svg xmlns="http://www.w3.org/2000/svg" width="15" height="13">
                <path
                  fill="#6E8098"
                  d="M15 6.495L8.766.014V3.88H7.441C3.33 3.88 0 7.039 0 10.936v2.049l.589-.612C2.59 10.294 5.422 9.11 8.39 9.11h.375v3.867L15 6.495z"
                />
              </svg>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
